---
# Per environment values which override defaults in hmpps-probation-check-in-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-check-in-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-check-in-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ESUPERVISION_API_URL: 'https://esupervision-api-preprod.hmpps.service.justice.gov.uk/v2'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_nonprod
