---
# Per environment values which override defaults in hmpps-probation-check-in-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-check-in-dev.hmpps.service.justice.gov.uk
    className: modsec-non-prod

  allowlist:
    groups:
      - internal

  env:
    INGRESS_URL: 'https://probation-check-in-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    ESUPERVISION_API_URL: 'https://esupervision-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: 'false'

generic-prometheus-alerts:
  alertSeverity: hmpps_probation_checkin_alerts_nonprod
