generic-service:
  nameOverride: hmpps-probation-check-in-ui
  productId: 'HMPPS9999' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-probation-check-in-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-probation-check-in-ui-cert

    # modsecurity
    modsecurity_enabled: true
    modsecurity_github_team: stg-pathfinders
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecAuditEngine RelevantOnly
      SecRequestBodyAccess On
      SecDefaultAction "phase:2,pass,log,tag:github_team=stg-pathfinders,tag:namespace={{ .Release.Namespace }}"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'false'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'UNASSIGNED' # Your audit service name

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-probation-check-in-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-probation-check-in-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    hmpps-probation-check-in-ui-elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-probation-check-in-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
    ip-info-token:
      IP_INFO_TOKEN: 'token'
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-probation-check-in-ui
